import type { Command, DetectionResult, Diagnostic, Repository, Symbol, Reference } from "../../shared/src/index.js";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { readFile } from "node:fs/promises";
export interface Location { file: string; line: number; column: number }
export interface HoverInformation { contents: string; range?: { start: Location; end: Location } }
export interface LanguageServer { initialize(): Promise<void>; definition(location: Location): Promise<Location[]>; references(location: Location): Promise<Location[]>; hover(location: Location): Promise<HoverInformation | undefined>; symbols(file: string): Promise<Symbol[]>; diagnostics(file: string): Promise<Diagnostic[]>; refresh(file: string): Promise<void>; shutdown(): Promise<void> }
/** Explicit null-object fallback ensures missing language servers never break repository work. */
export class UnavailableLanguageServer implements LanguageServer { constructor(private readonly reason = "Language server unavailable") {} async initialize() {} async definition() { return []; } async references() { return []; } async hover() { return { contents: this.reason }; } async symbols() { return []; } async diagnostics() { return []; } async refresh() {} async shutdown() {} }
interface PendingRequest { resolve(value: any): void; reject(error: Error): void; timer: NodeJS.Timeout }
const fromLspLocation = (value: any): Location => ({ file: value.uri?.replace(/^file:\/\//, "") ?? "", line: (value.range?.start?.line ?? 0) + 1, column: (value.range?.start?.character ?? 0) + 1 });
const toLspPosition = (location: Location) => ({ textDocument: { uri: `file://${location.file}` }, position: { line: Math.max(0, location.line - 1), character: Math.max(0, location.column - 1) } });
/** Generic Content-Length JSON-RPC client for tsserver wrappers, JDT LS, pyright, and other LSP servers. */
export class StdioLanguageServer implements LanguageServer {
  private readonly process: ChildProcessWithoutNullStreams; private readonly pending = new Map<number, PendingRequest>(); private readonly publishedDiagnostics = new Map<string, Diagnostic[]>(); private readonly opened = new Set<string>(); private readonly versions = new Map<string, number>(); private buffer = ""; private nextId = 1; private initialized = false; private failure?: Error;
  constructor(private readonly command: string, private readonly args: string[] = [], private readonly rootUri = `file://${process.cwd()}`, private readonly timeoutMs = 30_000) { this.process = spawn(command, args, { stdio: "pipe" }); this.process.stdout.setEncoding("utf8"); this.process.stdout.on("data", chunk => this.onData(chunk)); this.process.stdin.on("error", error => this.failAll(error)); this.process.on("error", error => this.failAll(error)); this.process.on("exit", () => this.failAll(new Error(`Language server ${command} exited`))); }
  private onData(chunk: string) { this.buffer += chunk; while (true) { const boundary = this.buffer.indexOf("\r\n\r\n"); if (boundary < 0) return; const header = this.buffer.slice(0, boundary); const match = header.match(/content-length:\s*(\d+)/i); if (!match) { this.buffer = ""; return; } const length = Number(match[1]); const bodyStart = boundary + 4; if (this.buffer.length < bodyStart + length) return; const body = this.buffer.slice(bodyStart, bodyStart + length); this.buffer = this.buffer.slice(bodyStart + length); try { const message = JSON.parse(body); if (message.method === "textDocument/publishDiagnostics") { const file = String(message.params?.uri ?? "").replace(/^file:\/\//, ""); this.publishedDiagnostics.set(file, (message.params?.diagnostics ?? []).map((item: any) => ({ file, line: (item.range?.start?.line ?? 0) + 1, severity: item.severity === 1 ? "error" : item.severity === 2 ? "warning" : "info", message: item.message ?? "" }))); } if (typeof message.id === "number") { const request = this.pending.get(message.id); if (request) { clearTimeout(request.timer); this.pending.delete(message.id); message.error ? request.reject(new Error(message.error.message ?? "LSP error")) : request.resolve(message.result); } } } catch { /* Keep processing subsequent framed messages. */ } } }
  private request(method: string, params: unknown): Promise<any> { if (this.failure) return Promise.reject(this.failure); const id = this.nextId++; const payload = JSON.stringify({ jsonrpc: "2.0", id, method, params }); return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(id); reject(new Error(`LSP ${method} timed out`)); }, this.timeoutMs); this.pending.set(id, { resolve, reject, timer }); try { this.process.stdin.write(`Content-Length: ${Buffer.byteLength(payload)}\r\n\r\n${payload}`, error => { if (error) this.failAll(error); }); } catch (error) { this.failAll(error instanceof Error ? error : new Error(String(error))); } }); }
  private notify(method: string, params: unknown) { if (this.failure) return; const payload = JSON.stringify({ jsonrpc: "2.0", method, params }); try { this.process.stdin.write(`Content-Length: ${Buffer.byteLength(payload)}\r\n\r\n${payload}`, error => { if (error) this.failAll(error); }); } catch (error) { this.failAll(error instanceof Error ? error : new Error(String(error))); } }
  private async open(file: string) { await this.initialize(); if (this.opened.has(file)) return; const text = await readFile(file, "utf8"); this.notify("textDocument/didOpen", { textDocument: { uri: `file://${file}`, languageId: file.endsWith(".py") ? "python" : file.endsWith(".java") ? "java" : "typescript", version: 1, text } }); this.opened.add(file); this.versions.set(file, 1); }
  private failAll(error: Error) { this.failure ??= error; for (const request of this.pending.values()) { clearTimeout(request.timer); request.reject(this.failure); } this.pending.clear(); }
  async initialize() { if (this.initialized) return; await this.request("initialize", { processId: process.pid, rootUri: this.rootUri, capabilities: {} }); this.notify("initialized", {}); this.initialized = true; }
  async definition(location: Location) { await this.open(location.file); const result = await this.request("textDocument/definition", toLspPosition(location)); return (Array.isArray(result) ? result : result ? [result] : []).map(fromLspLocation); }
  async references(location: Location) { await this.open(location.file); const result = await this.request("textDocument/references", { ...toLspPosition(location), context: { includeDeclaration: true } }); return (result ?? []).map(fromLspLocation); }
  async hover(location: Location) { await this.open(location.file); const result = await this.request("textDocument/hover", toLspPosition(location)); if (!result) return undefined; const contents = Array.isArray(result.contents) ? result.contents.map((item: any) => typeof item === "string" ? item : item.value ?? "").join("\n") : typeof result.contents === "string" ? result.contents : result.contents?.value ?? ""; return { contents }; }
  async symbols(file: string): Promise<Symbol[]> { await this.open(file); const result = await this.request("textDocument/documentSymbol", { textDocument: { uri: `file://${file}` } }); return (result ?? []).map((item: any) => ({ name: item.name, kind: String(item.kind), file, line: (item.selectionRange?.start?.line ?? item.range?.start?.line ?? 0) + 1, endLine: (item.range?.end?.line ?? 0) + 1 })); }
  async diagnostics(file: string) { await this.open(file); return this.publishedDiagnostics.get(file) ?? []; }
  async refresh(file: string) { if (!this.opened.has(file)) return; const version = (this.versions.get(file) ?? 1) + 1; this.notify("textDocument/didChange", { textDocument: { uri: `file://${file}`, version }, contentChanges: [{ text: await readFile(file, "utf8") }] }); this.versions.set(file, version); }
  async shutdown() { if (this.initialized) { await this.request("shutdown", {}); this.notify("exit", {}); } this.process.kill(); }
}
export interface LanguagePlugin { id: string; detect(repository: Repository): Promise<DetectionResult>; index(repository: Repository): Promise<void>; getSymbols(file: string): Promise<Symbol[]>; getReferences(symbol: string): Promise<Reference[]>; getDiagnostics(files: string[]): Promise<Diagnostic[]>; getBuildCommands(repository: Repository): Promise<Command[]>; getTestCommands(repository: Repository): Promise<Command[]>; getFormatCommands(repository: Repository): Promise<Command[]> }
export class LanguagePluginRegistry { private readonly plugins = new Map<string, LanguagePlugin>(); register(plugin: LanguagePlugin) { this.plugins.set(plugin.id, plugin); } all() { return [...this.plugins.values()]; } async detect(repository: Repository) { return Promise.all(this.all().map(async plugin => ({ plugin: plugin.id, result: await plugin.detect(repository) }))); } }
