import type { Diagnostic, Reference, Symbol, Task } from "../../shared/src/index.js";
import type { RepositoryContext, RepositoryKnowledgeProvider, RepositoryMap, RepositoryProfile } from "../../repository/src/index.js";
import type { FrameworkPlugin } from "../../framework-services/src/index.js";
import type { Repository } from "../../shared/src/index.js";
import type { LanguagePlugin } from "../../language-services/src/index.js";
/** Transport-neutral contract for a future Graphify API/client. */
export interface GraphifyClient { detectRepository(): Promise<RepositoryProfile>; getRepositoryMap(options?: { maxFiles?: number }): Promise<RepositoryMap>; search(query: { text: string; maxResults?: number }): Promise<Array<{ file: string; line: number; text: string }>>; getSymbols(query: { name?: string }): Promise<Symbol[]>; getDependencies(target: string): Promise<{ target: string; dependencies: string[] }>; getReferences(target: string): Promise<Reference[]>; getRelevantContext(task: Task): Promise<RepositoryContext> }
export class GraphifyRepositoryKnowledgeProvider implements RepositoryKnowledgeProvider {
  constructor(private readonly client: GraphifyClient) {}
  detectRepository = () => this.client.detectRepository(); getRepositoryMap = (options?: { maxFiles?: number }) => this.client.getRepositoryMap(options); search = (query: { text: string; maxResults?: number }) => this.client.search(query); getSymbols = (query: { name?: string }) => this.client.getSymbols(query); getDependencies = (target: string) => this.client.getDependencies(target); getReferences = (target: string) => this.client.getReferences(target); getRelevantContext = (task: Task) => this.client.getRelevantContext(task);
}
/** Uses fast local retrieval where sufficient and graph relationships where they carry more value. */
export class HybridRepositoryKnowledgeProvider implements RepositoryKnowledgeProvider {
  constructor(private readonly local: RepositoryKnowledgeProvider, private readonly graphify?: RepositoryKnowledgeProvider) {}
  detectRepository() { return this.local.detectRepository(); }
  getRepositoryMap(options?: { maxFiles?: number }) { return this.local.getRepositoryMap(options); }
  async search(query: { text: string; maxResults?: number }) { const local = await this.local.search(query); return local.length || !this.graphify ? local : this.graphify.search(query); }
  async getSymbols(query: { name?: string }) { const local = await this.local.getSymbols(query); return local.length || !this.graphify ? local : this.graphify.getSymbols(query); }
  getDependencies(target: string) { return this.graphify?.getDependencies(target) ?? this.local.getDependencies(target); }
  getReferences(target: string) { return this.graphify?.getReferences(target) ?? this.local.getReferences(target); }
  async getRelevantContext(task: Task) { const local = await this.local.getRelevantContext(task); if (!this.graphify) return local; try { const graph = await this.graphify.getRelevantContext(task); return { ...local, files: [...new Set([...local.files, ...graph.files])], symbols: [...new Map([...local.symbols, ...graph.symbols].map(symbol => [`${symbol.file}:${symbol.line}:${symbol.name}`, symbol])).values()], snippets: [...local.snippets, ...graph.snippets].slice(0, 20), tests: [...new Set([...local.tests, ...graph.tests])] }; } catch { return local; } }
  invalidate() { this.local.invalidate?.(); this.graphify?.invalidate?.(); }
}
/** Adds detected framework topology to an otherwise provider-independent repository context. */
export class FrameworkEnrichedRepositoryKnowledgeProvider implements RepositoryKnowledgeProvider {
  constructor(private readonly base: RepositoryKnowledgeProvider, private readonly repository: Repository, private readonly frameworks: FrameworkPlugin[]) {}
  detectRepository = () => this.base.detectRepository(); getRepositoryMap = (options?: { maxFiles?: number }) => this.base.getRepositoryMap(options); search = (query: { text: string; maxResults?: number }) => this.base.search(query); getSymbols = (query: { name?: string }) => this.base.getSymbols(query); getDependencies = (target: string) => this.base.getDependencies(target); getReferences = (target: string) => this.base.getReferences(target); invalidate = () => this.base.invalidate?.();
  getDiagnostics = (files?: string[]) => this.base.getDiagnostics?.(files) ?? Promise.resolve([]);
  async getRelevantContext(task: Task) { const context = await this.base.getRelevantContext(task); const framework = (await Promise.all(this.frameworks.map(async plugin => ({ plugin, detection: await plugin.detect(this.repository) })))).filter(item => item.detection.detected).map(async ({ plugin }) => ({ id: plugin.id, ...(await plugin.analyze(this.repository)) })); return { ...context, framework: await Promise.all(framework) }; }
}
/** Activates detected language plugins without coupling the core repository API to a language. */
export class LanguageEnrichedRepositoryKnowledgeProvider implements RepositoryKnowledgeProvider {
  private active?: LanguagePlugin[];
  constructor(private readonly base: RepositoryKnowledgeProvider, private readonly repository: Repository, private readonly plugins: LanguagePlugin[]) {}
  private async languages() { if (this.active) return this.active; const detected = await Promise.all(this.plugins.map(async plugin => ({ plugin, result: await plugin.detect(this.repository) }))); this.active = detected.filter(item => item.result.detected).map(item => item.plugin); await Promise.all(this.active.map(plugin => plugin.index(this.repository))); return this.active; }
  detectRepository = () => this.base.detectRepository(); getRepositoryMap = (options?: { maxFiles?: number }) => this.base.getRepositoryMap(options); search = (query: { text: string; maxResults?: number }) => this.base.search(query); getDependencies = (target: string) => this.base.getDependencies(target); invalidate = () => this.base.invalidate?.();
  async getReferences(target: string) { const references = [...await this.base.getReferences(target), ...(await Promise.all((await this.languages()).map(plugin => plugin.getReferences(target).catch(() => [])))).flat()]; return [...new Map(references.map(reference => [`${reference.file}:${reference.line}:${reference.target}`, reference])).values()]; }
  async getSymbols(query: { name?: string }) { const map = await this.base.getRepositoryMap({ maxFiles: 2_000 }); const extras = (await Promise.all((await this.languages()).map(async plugin => (await Promise.all(map.files.filter(file => /\.(?:ts|tsx|js|jsx|java|py)$/.test(file.path)).map(file => plugin.getSymbols(file.path).catch(() => [])))).flat()))).flat(); const merged = [...new Map([...(await this.base.getSymbols(query)), ...extras].map(symbol => [`${symbol.file}:${symbol.line}:${symbol.name}`, symbol])).values()]; return query.name ? merged.filter(symbol => symbol.name.toLowerCase().includes(query.name!.toLowerCase())) : merged; }
  async getDiagnostics(files?: string[]): Promise<Diagnostic[]> { const map = files ?? (await this.base.getRepositoryMap({ maxFiles: 2_000 })).files.map(file => file.path); return (await Promise.all((await this.languages()).map(plugin => plugin.getDiagnostics(map).catch(() => [])))).flat(); }
  async getRelevantContext(task: Task) { const context = await this.base.getRelevantContext(task); return { ...context, symbols: (await this.getSymbols({})).filter(symbol => task.prompt.toLowerCase().includes(symbol.name.toLowerCase())).slice(0, 40) }; }
}
/** Combines explicitly named repositories while preserving an unambiguous `id:path` namespace. */
export class MultiRepositoryKnowledgeProvider implements RepositoryKnowledgeProvider {
  constructor(private readonly repositories: Record<string, RepositoryKnowledgeProvider>, private readonly defaultRepository: string) { if (!repositories[defaultRepository]) throw new Error(`Default repository is not configured: ${defaultRepository}`); }
  private split(value: string) { const match = value.match(/^([A-Za-z0-9_-]+):(.*)$/); const id = match?.[1] ?? this.defaultRepository, path = match?.[2] ?? value, provider = this.repositories[id]; if (!provider) throw new Error(`Repository is not configured: ${id}`); return { id, path, provider }; }
  async detectRepository() { const profiles = await Promise.all(Object.entries(this.repositories).map(async ([id, provider]) => ({ id, profile: await provider.detectRepository() }))); return { root: profiles.map(item => `${item.id}:${item.profile.root}`).join(","), files: profiles.reduce((sum, item) => sum + item.profile.files, 0), languages: [...new Set(profiles.flatMap(item => item.profile.languages))], packageManagers: [...new Set(profiles.flatMap(item => item.profile.packageManagers))], markers: profiles.flatMap(item => item.profile.markers.map(marker => `${item.id}:${marker}`)) }; }
  async getRepositoryMap(options?: { maxFiles?: number }) { const maps = await Promise.all(Object.entries(this.repositories).map(async ([id, provider]) => ({ id, map: await provider.getRepositoryMap(options) }))); return { files: maps.flatMap(item => item.map.files.map(file => ({ ...file, path: `${item.id}:${file.path}` }))), truncated: maps.some(item => item.map.truncated) }; }
  async search(query: { text: string; maxResults?: number }) { const maxResults = query.maxResults ?? 30, results: Array<{ file: string; line: number; text: string }> = []; for (const [id, provider] of Object.entries(this.repositories)) { if (results.length >= maxResults) break; results.push(...(await provider.search({ ...query, maxResults: maxResults - results.length })).map(result => ({ ...result, file: `${id}:${result.file}` }))); } return results; }
  async getSymbols(query: { name?: string }) { return (await Promise.all(Object.entries(this.repositories).map(async ([id, provider]) => (await provider.getSymbols(query)).map(symbol => ({ ...symbol, file: `${id}:${symbol.file}` }))))).flat(); }
  async getDependencies(target: string) { const { id, path, provider } = this.split(target); const result = await provider.getDependencies(path); return { target: `${id}:${result.target}`, dependencies: result.dependencies.map(dependency => dependency.startsWith(".") ? `${id}:${dependency}` : dependency) }; }
  async getReferences(target: string) { const { id, path, provider } = this.split(target); return (await provider.getReferences(path)).map(reference => ({ ...reference, file: `${id}:${reference.file}`, target })); }
  async getRelevantContext(task: Task) { const contexts = await Promise.all(Object.entries(this.repositories).map(async ([id, provider]) => ({ id, context: await provider.getRelevantContext(task) }))); return { map: await this.getRepositoryMap({ maxFiles: 500 }), symbols: contexts.flatMap(item => item.context.symbols.map(symbol => ({ ...symbol, file: `${item.id}:${symbol.file}` }))), files: contexts.flatMap(item => item.context.files.map(file => `${item.id}:${file}`)), snippets: contexts.flatMap(item => item.context.snippets.map(snippet => ({ ...snippet, file: `${item.id}:${snippet.file}` }))), tests: contexts.flatMap(item => item.context.tests.map(test => `${item.id}:${test}`)), framework: contexts.flatMap(item => item.context.framework ?? []) }; }
  async getDiagnostics(files?: string[]) { const diagnostics: Diagnostic[] = []; for (const [id, provider] of Object.entries(this.repositories)) { const local = files?.filter(file => file.startsWith(`${id}:`)).map(file => file.slice(id.length + 1)); diagnostics.push(...((await provider.getDiagnostics?.(local) ?? []).map(diagnostic => ({ ...diagnostic, file: `${id}:${diagnostic.file}` })))); } return diagnostics; }
  invalidate() { Object.values(this.repositories).forEach(provider => provider.invalidate?.()); }
}
