import { access, readFile } from "node:fs/promises";
import { join } from "node:path";
import ts from "typescript";
import type { LanguagePlugin } from "../../../packages/language-services/src/index.js";
import type { Diagnostic, Repository, Symbol } from "../../../packages/shared/src/index.js";
const exists = (path: string) => access(path).then(() => true).catch(() => false);
async function packageManager(repository: Repository) { const pkg = await readFile(join(repository.root, "package.json"), "utf8").catch(() => ""); try { const value = (JSON.parse(pkg) as { packageManager?: string }).packageManager?.split("@")[0]; if (["npm", "pnpm", "yarn", "bun"].includes(value ?? "")) return value!; } catch { /* Fall through to lockfile detection. */ } if (await exists(join(repository.root, "pnpm-lock.yaml"))) return "pnpm"; if (await exists(join(repository.root, "yarn.lock"))) return "yarn"; if (await exists(join(repository.root, "bun.lock")) || await exists(join(repository.root, "bun.lockb"))) return "bun"; return "npm"; }
export class TypeScriptPlugin implements LanguagePlugin {
  id = "typescript"; private root?: string;
  async detect(repository: Repository) { const pkg = await readFile(join(repository.root, "package.json"), "utf8").catch(() => ""); const config = await exists(join(repository.root, "tsconfig.json")); return { detected: config || /typescript|react|next|vite/.test(pkg), confidence: config ? .95 : /typescript/.test(pkg) ? .8 : 0, evidence: [config && "tsconfig.json", /typescript/.test(pkg) && "package.json"].filter(Boolean) as string[] }; }
  async index(repository: Repository) { this.root = repository.root; }
  async getSymbols(file: string): Promise<Symbol[]> { if (!this.root) throw new Error("TypeScriptPlugin.index(repository) must run first"); const text = await readFile(join(this.root, file), "utf8"); const source = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, file.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS); const symbols: Symbol[] = []; const visit = (node: ts.Node) => { const name = "name" in node ? (node as ts.NamedDeclaration).name : undefined; if (name && ts.isIdentifier(name) && (ts.isFunctionDeclaration(node) || ts.isClassDeclaration(node) || ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node) || ts.isEnumDeclaration(node))) symbols.push({ name: name.text, kind: ts.SyntaxKind[node.kind].replace("Declaration", "").toLowerCase(), file, line: source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1, exported: ts.canHaveModifiers(node) && Boolean(ts.getModifiers(node)?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword)) }); ts.forEachChild(node, visit); }; ts.forEachChild(source, visit); return symbols; }
  async getReferences() { return []; }
  async getDiagnostics(files: string[]): Promise<Diagnostic[]> { if (!this.root) return []; const diagnostics: Diagnostic[] = []; for (const file of files) { const output = ts.transpileModule(await readFile(join(this.root, file), "utf8").catch(() => ""), { reportDiagnostics: true, compilerOptions: { target: ts.ScriptTarget.ES2022 } }); output.diagnostics?.forEach(diagnostic => diagnostics.push({ file, severity: "error", message: ts.flattenDiagnosticMessageText(diagnostic.messageText, " ") })); } return diagnostics; }
  async getBuildCommands(repository: Repository) { if (!(await exists(join(repository.root, "package.json")))) return []; const manager = await packageManager(repository); return [{ argv: manager === "npm" ? ["npm", "run", "build"] : [manager, "build"] }]; }
  async getTestCommands(repository: Repository) { if (!(await exists(join(repository.root, "package.json")))) return []; const manager = await packageManager(repository); return [{ argv: [manager, "test"] }]; }
  async getFormatCommands() { return []; }
}
