import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { randomUUID } from "node:crypto";
import type { AgentEvent } from "../../../packages/protocol/src/index.js";
export interface AgentRunRequest { task: string; workspace: string; maxTurns?: number; permissionMode?: "review" | "accept-edits" | "auto"; sessionId?: string; resume?: boolean; signal?: AbortSignal }
export interface AgentRunHandler { run(request: AgentRunRequest): Promise<unknown>; runStreaming?(request: AgentRunRequest, emit: (event: AgentEvent) => Promise<void>): Promise<unknown> }
export interface ServerOptions { apiKey?: string; maxRequestsPerMinute?: number; now?: () => number }
export interface BackgroundRun { sessionId: string; state: "running" | "completed" | "failed" | "cancelled"; result?: unknown; events: AgentEvent[] }
async function jsonBody(request: IncomingMessage): Promise<unknown> { const chunks: Buffer[] = []; let size = 0; for await (const chunk of request) { size += chunk.length; if (size > 1_000_000) throw new Error("Request body exceeds 1 MB"); chunks.push(chunk); } return JSON.parse(Buffer.concat(chunks).toString("utf8")); }
function json(response: ServerResponse, status: number, body: unknown) { response.writeHead(status, { "content-type": "application/json" }); response.end(JSON.stringify(body)); }
export async function parseRun(body: unknown): Promise<AgentRunRequest> { const input = body as Partial<AgentRunRequest>; if (typeof input.task !== "string" || !input.task.trim() || typeof input.workspace !== "string") throw new Error("task and workspace are required strings"); if (input.maxTurns !== undefined && (!Number.isInteger(input.maxTurns) || input.maxTurns < 1 || input.maxTurns > 100)) throw new Error("maxTurns must be an integer from 1 to 100"); if (input.permissionMode !== undefined && !["review", "accept-edits", "auto"].includes(input.permissionMode)) throw new Error("invalid permissionMode"); if (input.sessionId !== undefined && (typeof input.sessionId !== "string" || !/^[A-Za-z0-9_-]{1,128}$/.test(input.sessionId))) throw new Error("invalid sessionId"); if (input.resume !== undefined && typeof input.resume !== "boolean") throw new Error("resume must be a boolean"); if (input.resume && !input.sessionId) throw new Error("resume requires sessionId"); return { task: input.task, workspace: input.workspace, maxTurns: input.maxTurns, permissionMode: input.permissionMode ?? "review", sessionId: input.sessionId, resume: input.resume }; }
export async function handleRun(body: unknown, handler: AgentRunHandler) { return handler.run(await parseRun(body)); }
/** HTTP transport with optional bearer auth, per-client limiting, and Server-Sent Event progress. */
export function createAgentServer(handler: AgentRunHandler, options: ServerOptions = {}): Server {
  const hits = new Map<string, number[]>(), background = new Map<string, BackgroundRun & { controller: AbortController }>(), now = options.now ?? Date.now;
  return createServer(async (request, response) => { try {
    if (request.method === "GET" && request.url === "/health") return json(response, 200, { ok: true });
    const runStatus = request.url?.match(/^\/runs\/([A-Za-z0-9_-]{1,128})$/);
    if (request.method === "GET" && runStatus) { if (options.apiKey && request.headers.authorization !== `Bearer ${options.apiKey}`) return json(response, 401, { error: "Unauthorized" }); const run = background.get(runStatus[1]!); return run ? json(response, 200, { sessionId: run.sessionId, state: run.state, result: run.result, events: run.events }) : json(response, 404, { error: "Run not found" }); }
    if (request.method === "DELETE" && runStatus) { if (options.apiKey && request.headers.authorization !== `Bearer ${options.apiKey}`) return json(response, 401, { error: "Unauthorized" }); const run = background.get(runStatus[1]!); if (!run) return json(response, 404, { error: "Run not found" }); if (run.state === "running") { run.controller.abort(); run.state = "cancelled"; } return json(response, 202, { sessionId: run.sessionId, state: run.state }); }
    if (request.method !== "POST" || !["/runs", "/runs/stream", "/runs/background"].includes(request.url ?? "")) return json(response, 404, { error: "Not found" });
    if (options.apiKey && request.headers.authorization !== `Bearer ${options.apiKey}`) return json(response, 401, { error: "Unauthorized" });
    const client = request.socket.remoteAddress ?? "unknown", cutoff = now() - 60_000, recent = (hits.get(client) ?? []).filter(time => time > cutoff);
    if (options.maxRequestsPerMinute && recent.length >= options.maxRequestsPerMinute) return json(response, 429, { error: "Rate limit exceeded" }); recent.push(now()); hits.set(client, recent);
    const run = await parseRun(await jsonBody(request));
    if (request.url === "/runs") return json(response, 200, await handler.run(run));
    if (request.url === "/runs/background") { const sessionId = run.sessionId ?? randomUUID(); if (background.size >= 100) { const oldest = background.keys().next().value as string | undefined; if (oldest) background.delete(oldest); } const tracked: BackgroundRun & { controller: AbortController } = { sessionId, state: "running", events: [], controller: new AbortController() }; background.set(sessionId, tracked); void (async () => { try { tracked.result = handler.runStreaming ? await handler.runStreaming({ ...run, sessionId, signal: tracked.controller.signal }, async event => { if (tracked.events.length >= 1_000) tracked.events.shift(); tracked.events.push(event); }) : await handler.run({ ...run, sessionId, signal: tracked.controller.signal }); if (tracked.state === "running") tracked.state = (tracked.result as { state?: string } | undefined)?.state === "cancelled" ? "cancelled" : "completed"; } catch (error) { if (tracked.state === "running") tracked.state = "failed"; tracked.result = { error: error instanceof Error ? error.message : String(error) }; } })(); return json(response, 202, { sessionId, state: "running" }); }
    response.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive" });
    const emit = async (event: AgentEvent) => { response.write(`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`); };
    const result = handler.runStreaming ? await handler.runStreaming(run, emit) : await handler.run(run); response.write(`event: completed\ndata: ${JSON.stringify(result)}\n\n`); response.end();
  } catch (error) { if (!response.headersSent) return json(response, 400, { error: error instanceof Error ? error.message : "Bad request" }); response.end(); } });
}
