import { mkdir, readdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { basename, join, relative } from "node:path";
import ts from "typescript";
import type { Diagnostic, Repository, Symbol, Reference, Task } from "../../shared/src/index.js";

export interface RepositoryProfile { root: string; files: number; languages: string[]; packageManagers: string[]; markers: string[] }
export interface RepositoryMap { files: Array<{ path: string; bytes: number }>; truncated: boolean }
export interface SourceExcerpt { file: string; startLine: number; endLine: number; content: string; relevance: number }
export interface RepositoryContext { map: RepositoryMap; symbols: Symbol[]; files: string[]; snippets: SourceExcerpt[]; tests: string[]; framework?: Array<{ id: string; nodes: unknown[]; edges: Array<[string, string]> }> }
export interface RepositoryKnowledgeProvider { detectRepository(): Promise<RepositoryProfile>; getRepositoryMap(options?: { maxFiles?: number }): Promise<RepositoryMap>; search(query: { text: string; maxResults?: number }): Promise<Array<{ file: string; line: number; text: string }>>; getSymbols(query: { name?: string }): Promise<Symbol[]>; getDependencies(target: string): Promise<{ target: string; dependencies: string[] }>; getReferences(target: string): Promise<Reference[]>; getRelevantContext(task: Task): Promise<RepositoryContext>; getDiagnostics?(files?: string[]): Promise<Diagnostic[]>; invalidate?(): void }

const ignored = new Set([".git", ".agent", "node_modules", "dist", "build", ".next", "target", "__pycache__"]);
const codeFile = (file: string) => /\.(ts|tsx|mts|cts|js|jsx|py|pyi|java)$/.test(file);
const tsFile = (file: string) => /\.(ts|tsx|mts|cts|js|jsx)$/.test(file);
async function files(root: string, at = root, out: string[] = []): Promise<string[]> { for (const entry of await readdir(at, { withFileTypes: true })) { if (ignored.has(entry.name)) continue; const full = join(at, entry.name); if (entry.isDirectory()) await files(root, full, out); else if (entry.isFile()) out.push(relative(root, full)); } return out; }
function exported(node: ts.Node) { return ts.canHaveModifiers(node) && Boolean(ts.getModifiers(node)?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword)); }
function nameOf(node: ts.Node): string | undefined { const name = (node as ts.NamedDeclaration).name; return name && ts.isIdentifier(name) ? name.text : undefined; }
function tsSymbols(file: string, source: string): Symbol[] { const sourceFile = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, file.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS); const result: Symbol[] = []; const add = (node: ts.Node, kind: string, name = nameOf(node), isExported = exported(node)) => { if (!name) return; result.push({ name, kind, file, line: sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1, endLine: sourceFile.getLineAndCharacterOfPosition(node.getEnd()).line + 1, exported: isExported }); }; const visit = (node: ts.Node) => { if (ts.isFunctionDeclaration(node)) add(node, "function"); else if (ts.isClassDeclaration(node)) add(node, "class"); else if (ts.isInterfaceDeclaration(node)) add(node, "interface"); else if (ts.isTypeAliasDeclaration(node)) add(node, "type"); else if (ts.isEnumDeclaration(node)) add(node, "enum"); else if (ts.isVariableStatement(node)) node.declarationList.declarations.forEach(declaration => add(declaration, "variable", ts.isIdentifier(declaration.name) ? declaration.name.text : undefined, exported(node))); ts.forEachChild(node, visit); }; ts.forEachChild(sourceFile, visit); return result; }
function polyglotSymbols(file: string, source: string): Symbol[] { const result: Symbol[] = []; source.split(/\r?\n/).forEach((line, index) => { const java = line.match(/^\s*(?:public|protected|private|abstract|final|static|sealed|non-sealed|\s)*\b(class|interface|enum|record)\s+([A-Za-z_$][\w$]*)/) ?? line.match(/^\s*(?:public|protected|private|static|final|synchronized|abstract|native|\s)+[\w$.<>\[\], ?]+\s+([A-Za-z_$][\w$]*)\s*\([^;]*\)\s*(?:\{|throws\b)/); const python = line.match(/^\s*(?:async\s+)?def\s+([A-Za-z_]\w*)\s*\(/) ?? line.match(/^\s*class\s+([A-Za-z_]\w*)\b/); if (java) { const isType = java.length > 2; result.push({ name: isType ? java[2]! : java[1]!, kind: isType ? java[1]! : "method", file, line: index + 1, exported: /^\s*public\b/.test(line) }); } else if (python) result.push({ name: python[1]!, kind: /^\s*class\b/.test(line) ? "class" : "function", file, line: index + 1, exported: !python[1]!.startsWith("_") }); }); return result; }

export class LocalRepositoryKnowledgeProvider implements RepositoryKnowledgeProvider {
  constructor(private readonly repository: Repository) {}
  private allFiles?: string[]; private indexedSymbols?: Symbol[]; private symbolEntries?: Map<string, { size: number; mtimeMs: number; symbols: Symbol[] }>; private diskCacheLoaded = false;
  invalidate() { this.allFiles = undefined; this.indexedSymbols = undefined; }
  private async list() { return this.allFiles ??= await files(this.repository.root); }
  private async source(file: string) { return readFile(join(this.repository.root, file), "utf8").catch(() => ""); }
  private get cachePath() { return join(this.repository.root, ".agent", "index", "symbols-v1.json"); }
  private async loadSymbolCache() { if (this.diskCacheLoaded) return; this.diskCacheLoaded = true; const raw = await readFile(this.cachePath, "utf8").catch(() => ""); try { const parsed = JSON.parse(raw) as { version: number; entries: Record<string, { size: number; mtimeMs: number; symbols: Symbol[] }> }; if (parsed.version === 1 && parsed.entries && typeof parsed.entries === "object") this.symbolEntries = new Map(Object.entries(parsed.entries)); } catch { /* A corrupt cache is disposable and rebuilt below. */ } }
  private async saveSymbolCache() { if (!this.symbolEntries) return; await mkdir(join(this.repository.root, ".agent", "index"), { recursive: true }); const temporary = `${this.cachePath}.tmp`; await writeFile(temporary, JSON.stringify({ version: 1, entries: Object.fromEntries(this.symbolEntries) }), { mode: 0o600 }); await rename(temporary, this.cachePath); }
  private async buildSymbolIndex() { if (this.indexedSymbols) return this.indexedSymbols; await this.loadSymbolCache(); const next = new Map<string, { size: number; mtimeMs: number; symbols: Symbol[] }>(); for (const file of (await this.list()).filter(codeFile)) { const info = await stat(join(this.repository.root, file)); const cached = this.symbolEntries?.get(file); if (cached && cached.size === info.size && cached.mtimeMs === info.mtimeMs) { next.set(file, cached); continue; } const source = await this.source(file); next.set(file, { size: info.size, mtimeMs: info.mtimeMs, symbols: tsFile(file) ? tsSymbols(file, source) : polyglotSymbols(file, source) }); } this.symbolEntries = next; await this.saveSymbolCache().catch(() => undefined); return this.indexedSymbols = [...next.values()].flatMap(entry => entry.symbols); }
  async detectRepository(): Promise<RepositoryProfile> { const paths = await this.list(); const languages = [...new Set(paths.map(f => tsFile(f) ? "typescript" : f.endsWith(".java") ? "java" : /\.pyi?$/.test(f) ? "python" : "").filter(Boolean))]; const markers = paths.filter(f => ["package.json", "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts", "pyproject.toml", "requirements.txt", "Pipfile", "setup.py", "setup.cfg"].includes(f) || /^requirements\/[^/]+\.txt$/.test(f)); const packageManagers = [paths.includes("pnpm-lock.yaml") && "pnpm", paths.includes("yarn.lock") && "yarn", paths.includes("package-lock.json") && "npm", (paths.includes("bun.lock") || paths.includes("bun.lockb")) && "bun", paths.includes("poetry.lock") && "poetry", paths.includes("uv.lock") && "uv", paths.includes("Pipfile.lock") && "pipenv", (paths.includes("requirements.txt") || paths.some(path => /^requirements\/[^/]+\.txt$/.test(path))) && "pip"].filter(Boolean) as string[]; return { root: this.repository.root, files: paths.length, languages, packageManagers, markers }; }
  async getRepositoryMap({ maxFiles = 500 } = {}): Promise<RepositoryMap> { const paths = await this.list(); return { files: await Promise.all(paths.slice(0, maxFiles).map(async path => ({ path, bytes: (await stat(join(this.repository.root, path))).size }))), truncated: paths.length > maxFiles }; }
  async search({ text, maxResults = 30 }: { text: string; maxResults?: number }) { const results: Array<{ file: string; line: number; text: string }> = []; for (const file of await this.list()) { if (results.length >= maxResults) break; const raw = await this.source(file); raw.split(/\r?\n/).forEach((line, i) => { if (results.length < maxResults && line.toLowerCase().includes(text.toLowerCase())) results.push({ file, line: i + 1, text: line.trim() }); }); } return results; }
  async getSymbols({ name }: { name?: string }) { const indexed = await this.buildSymbolIndex(); return name ? indexed.filter(symbol => symbol.name.toLowerCase().includes(name.toLowerCase())) : indexed; }
  async getDependencies(target: string) { const raw = await this.source(target); if (tsFile(target)) { const sourceFile = ts.createSourceFile(target, raw, ts.ScriptTarget.Latest, false); const dependencies = sourceFile.statements.flatMap(statement => { const moduleSpecifier = (ts.isImportDeclaration(statement) || ts.isExportDeclaration(statement)) ? statement.moduleSpecifier : undefined; return moduleSpecifier && ts.isStringLiteral(moduleSpecifier) ? [moduleSpecifier.text] : []; }).concat([...raw.matchAll(/require\(["']([^"']+)/g)].map(match => match[1]!)); return { target, dependencies: [...new Set(dependencies)] }; } const dependencies = target.endsWith(".java") ? [...raw.matchAll(/^\s*import\s+(?:static\s+)?([\w.*]+)\s*;/gm)].map(match => match[1]!) : [...raw.matchAll(/^\s*(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))/gm)].map(match => match[1] ?? match[2]!).filter(Boolean); return { target, dependencies: [...new Set(dependencies)] }; }
  async getReferences(target: string) { const matches = await this.search({ text: target, maxResults: 100 }); return matches.map(({ file, line }) => ({ file, line, target })); }
  async getRelevantContext(task: Task): Promise<RepositoryContext> { const terms = [...new Set(task.prompt.split(/\W+/).filter(word => word.length > 3).slice(0, 8))]; const hits = (await Promise.all(terms.map(text => this.search({ text, maxResults: 8 })))).flat(); const uniqueHits = [...new Map(hits.map(hit => [`${hit.file}:${hit.line}`, hit])).values()]; const snippets: SourceExcerpt[] = []; for (const hit of uniqueHits.slice(0, 12)) { const lines = (await this.source(hit.file)).split(/\r?\n/); const start = Math.max(0, hit.line - 3); const end = Math.min(lines.length, hit.line + 3); snippets.push({ file: hit.file, startLine: start + 1, endLine: end, content: lines.slice(start, end).join("\n"), relevance: 1 }); } const filenames = [...new Set(uniqueHits.map(hit => hit.file))]; const tests = (await this.list()).filter(file => /(?:^|\/)(?:test|tests|__tests__)\//.test(file) || /\.(test|spec)\.[^.]+$/.test(file)); const normalized = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, ""); const relatedTests = tests.filter(test => terms.some(term => normalized(basename(test)).includes(normalized(term)))); return { map: await this.getRepositoryMap({ maxFiles: 100 }), symbols: (await this.getSymbols({})).filter(symbol => terms.some(term => symbol.name.toLowerCase().includes(term.toLowerCase()))).slice(0, 40), files: filenames, snippets, tests: relatedTests }; }
}
