import { access, readdir, readFile, stat } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { join, relative } from "node:path";
import type { LanguagePlugin } from "../../../packages/language-services/src/index.js";
import type { Diagnostic, Repository, Symbol } from "../../../packages/shared/src/index.js";
const exists = (path: string) => access(path).then(() => true).catch(() => false);
const execFileAsync = promisify(execFile);
const astProgram = "import ast,json,sys\ntry:\n tree=ast.parse(open(sys.argv[1], encoding='utf8').read(), filename=sys.argv[1])\n symbols=[{'name':n.name,'kind':'class' if isinstance(n,ast.ClassDef) else 'function','line':n.lineno,'endLine':getattr(n,'end_lineno',n.lineno)} for n in ast.walk(tree) if isinstance(n,(ast.ClassDef,ast.FunctionDef,ast.AsyncFunctionDef))]\n references=[{'name':n.id if isinstance(n,ast.Name) else n.attr,'line':n.lineno} for n in ast.walk(tree) if isinstance(n,(ast.Name,ast.Attribute))]\n print(json.dumps({'symbols':symbols,'references':references}))\nexcept SyntaxError as e:\n print(json.dumps({'error':{'line':e.lineno or 1,'message':e.msg}}))";
async function pythonAst(path: string): Promise<{ symbols: Array<{ name: string; kind: string; line: number; endLine: number }>; references?: Array<{ name: string; line: number }>; error?: { line: number; message: string } } | undefined> { for (const command of ["python", "python3"]) try { const { stdout } = await execFileAsync(command, ["-c", astProgram, path], { timeout: 5_000, maxBuffer: 1_000_000 }); return JSON.parse(stdout) as { symbols: Array<{ name: string; kind: string; line: number; endLine: number }>; references?: Array<{ name: string; line: number }>; error?: { line: number; message: string } }; } catch { /* Try the next conventional interpreter name. */ } return undefined; }
async function pythonFiles(root: string, at = root, output: string[] = []): Promise<string[]> { for (const entry of await readdir(at, { withFileTypes: true }).catch(() => [])) { if ([".git", ".agent", "__pycache__", ".venv", "venv"].includes(entry.name)) continue; const full = join(at, entry.name); if (entry.isDirectory()) await pythonFiles(root, full, output); else if (entry.isFile() && /\.pyi?$/.test(entry.name)) output.push(relative(root, full)); } return output; }
export class PythonPlugin implements LanguagePlugin {
  id = "python"; private root?: string; private readonly astCache = new Map<string, { fingerprint: string; result?: Awaited<ReturnType<typeof pythonAst>> }>();
  async detect(repository: Repository) { const names = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", "Pipfile", "poetry.lock", "uv.lock"]; const found = (await Promise.all(names.map(name => exists(join(repository.root, name))))).map((yes, index) => yes ? names[index]! : undefined).filter((name): name is string => Boolean(name)); return { detected: found.length > 0, confidence: found.length ? .9 : 0, evidence: found }; }
  async index(repository: Repository) { this.root = repository.root; this.astCache.clear(); }
  private async parse(file: string) { if (!this.root) return undefined; const path = join(this.root, file), metadata = await stat(path).catch(() => undefined), fingerprint = metadata ? `${metadata.mtimeMs}:${metadata.size}` : "missing", cached = this.astCache.get(path); if (cached?.fingerprint === fingerprint) return cached.result; const result = await pythonAst(path); this.astCache.set(path, { fingerprint, result }); return result; }
  async getSymbols(file: string): Promise<Symbol[]> { if (!this.root) throw new Error("PythonPlugin.index(repository) must run first"); const parsed = await this.parse(file); if (parsed?.symbols) return parsed.symbols.map(symbol => ({ ...symbol, file })); return (await readFile(join(this.root, file), "utf8")).split(/\r?\n/).flatMap((line, index) => { const match = line.match(/^\s*(?:async\s+)?(def|class)\s+(\w+)/); return match ? [{ name: match[2]!, kind: match[1] === "class" ? "class" : "function", file, line: index + 1 }] : []; }); }
  async getReferences(symbol: string) { if (!this.root) return []; const references: Array<{ file: string; line: number; target: string }> = []; for (const file of await pythonFiles(this.root)) { const parsed = await this.parse(file); if (parsed?.references) references.push(...parsed.references.filter(reference => reference.name === symbol).map(reference => ({ file, line: reference.line, target: symbol }))); else { const expression = new RegExp(`\\b${symbol.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`); (await readFile(join(this.root, file), "utf8")).split(/\r?\n/).forEach((line, index) => { if (expression.test(line)) references.push({ file, line: index + 1, target: symbol }); }); } } return references; }
  async getDiagnostics(files: string[]): Promise<Diagnostic[]> { if (!this.root) return []; const diagnostics: Diagnostic[] = []; for (const file of files.filter(file => /\.pyi?$/.test(file))) { const parsed = await this.parse(file); if (parsed?.error) { diagnostics.push({ file, line: parsed.error.line, severity: "error", message: parsed.error.message }); continue; } const source = await readFile(join(this.root, file), "utf8").catch(() => ""); let depth = 0; source.split(/\r?\n/).forEach((line, index) => { depth += (line.match(/[\[({]/g) ?? []).length - (line.match(/[\])}]/g) ?? []).length; if (depth < 0) diagnostics.push({ file, line: index + 1, severity: "error", message: "Unbalanced closing delimiter" }); }); } return diagnostics; }
  async getBuildCommands(repository: Repository) { if (await exists(join(repository.root, "poetry.lock"))) return [{ argv: ["poetry", "build"] }]; if (await exists(join(repository.root, "pyproject.toml")) || await exists(join(repository.root, "setup.py"))) return [{ argv: ["python", "-m", "build"] }]; return []; }
  async getTestCommands(repository: Repository) { if (await exists(join(repository.root, "uv.lock"))) return [{ argv: ["uv", "run", "pytest"] }]; if (await exists(join(repository.root, "poetry.lock"))) return [{ argv: ["poetry", "run", "pytest"] }]; if (await exists(join(repository.root, "Pipfile"))) return [{ argv: ["pipenv", "run", "pytest"] }]; if (await exists(join(repository.root, "pyproject.toml")) || await exists(join(repository.root, "requirements.txt"))) return [{ argv: ["python", "-m", "pytest"] }]; return []; }
  async getFormatCommands() { return []; }
}
