import type { Json } from "../../shared/src/index.js";
export interface ModelCapabilities { toolCalling: boolean; structuredOutput: boolean; vision: boolean; reasoning: boolean; maxContextTokens: number }
export type ModelPurpose = "planning" | "coding" | "exploration" | "summarization" | "review" | "commit_message";
export interface ModelRequest { signal?: AbortSignal; messages: Array<{ role: "system" | "user" | "tool" | "assistant"; content: string }>; tools?: ModelTool[]; purpose?: ModelPurpose }
export interface ModelTool { name: string; description: string; inputSchema: Json }
export type ModelResponse = { kind: "text"; text: string; usage?: { inputTokens: number; outputTokens: number } } | { kind: "tool_calls"; calls: Array<{ id: string; name: string; input: unknown }> };
export interface ModelProvider { id: string; capabilities: ModelCapabilities; generate(request: ModelRequest): Promise<ModelResponse>; stream?(request: ModelRequest): AsyncIterable<ModelResponse> }
/** Selects a healthy provider while keeping provider-specific behavior outside the agent runtime. */
export class ModelRouter implements ModelProvider {
  id = "router";
  capabilities: ModelCapabilities;
  constructor(private readonly providers: ModelProvider[]) { if (!providers.length) throw new Error("ModelRouter requires at least one provider"); this.capabilities = { toolCalling: providers.some(provider => provider.capabilities.toolCalling), structuredOutput: providers.some(provider => provider.capabilities.structuredOutput), vision: providers.some(provider => provider.capabilities.vision), reasoning: providers.some(provider => provider.capabilities.reasoning), maxContextTokens: Math.max(...providers.map(provider => provider.capabilities.maxContextTokens)) }; }
  private eligible(request: ModelRequest) { return this.providers.filter(provider => !request.tools?.length || provider.capabilities.toolCalling); }
  async generate(request: ModelRequest): Promise<ModelResponse> { let lastError: unknown; for (const provider of this.eligible(request)) { try { return await provider.generate(request); } catch (error) { request.signal?.throwIfAborted(); lastError = error; } } throw lastError ?? new Error("No model provider supports this request"); }
  async *stream(request: ModelRequest): AsyncIterable<ModelResponse> { let lastError: unknown; for (const provider of this.eligible(request)) { try { if (provider.stream) { yield* provider.stream(request); return; } yield await provider.generate(request); return; } catch (error) { request.signal?.throwIfAborted(); lastError = error; } } throw lastError ?? new Error("No model provider supports this request"); }
}
/** Routes named agent purposes to dedicated models while retaining a compatible fallback. */
export class PurposeModelRouter implements ModelProvider {
  id = "purpose-router";
  capabilities: ModelCapabilities;
  constructor(private readonly fallback: ModelProvider, private readonly byPurpose: Partial<Record<ModelPurpose, ModelProvider>>) { this.capabilities = { ...fallback.capabilities, toolCalling: [fallback, ...Object.values(byPurpose)].some(provider => provider?.capabilities.toolCalling), structuredOutput: [fallback, ...Object.values(byPurpose)].some(provider => provider?.capabilities.structuredOutput), vision: [fallback, ...Object.values(byPurpose)].some(provider => provider?.capabilities.vision), reasoning: [fallback, ...Object.values(byPurpose)].some(provider => provider?.capabilities.reasoning), maxContextTokens: Math.max(fallback.capabilities.maxContextTokens, ...Object.values(byPurpose).flatMap(provider => provider ? [provider.capabilities.maxContextTokens] : [])) }; }
  private selected(request: ModelRequest) { const preferred = request.purpose ? this.byPurpose[request.purpose] ?? this.fallback : this.fallback; return request.tools?.length && !preferred.capabilities.toolCalling && this.fallback.capabilities.toolCalling ? this.fallback : preferred; }
  generate(request: ModelRequest) { return this.selected(request).generate(request); }
  async *stream(request: ModelRequest): AsyncIterable<ModelResponse> { const provider = this.selected(request); if (provider.stream) yield* provider.stream(request); else yield await provider.generate(request); }
}
export class ScriptedModelProvider implements ModelProvider { id = "scripted"; capabilities = { toolCalling: true, structuredOutput: true, vision: false, reasoning: false, maxContextTokens: 16_000 }; constructor(private readonly responses: ModelResponse[]) {} async generate(): Promise<ModelResponse> { return this.responses.shift() ?? { kind: "text", text: "Complete." }; } }
export interface OpenAICompatibleOptions { baseUrl: string; apiKey: string; model: string; headers?: Record<string, string> }
/** Minimal adapter for OpenAI-compatible Chat Completions endpoints. */
export class OpenAICompatibleProvider implements ModelProvider {
  id = "openai-compatible"; capabilities = { toolCalling: true, structuredOutput: true, vision: false, reasoning: false, maxContextTokens: 128_000 };
  constructor(private readonly options: OpenAICompatibleOptions) {}
  async generate(request: ModelRequest): Promise<ModelResponse> {
    const response = await fetch(`${this.options.baseUrl.replace(/\/$/, "")}/chat/completions`, { method: "POST", signal: request.signal, headers: { "content-type": "application/json", authorization: `Bearer ${this.options.apiKey}`, ...this.options.headers }, body: JSON.stringify({ model: this.options.model, messages: request.messages, tools: request.tools?.map(tool => ({ type: "function", function: { name: tool.name, description: tool.description, parameters: tool.inputSchema } })), tool_choice: "auto" }) });
    if (!response.ok) throw new Error(`Model request failed (${response.status}): ${(await response.text()).slice(0, 500)}`);
    const body = await response.json() as any; const message = body.choices?.[0]?.message;
    if (!message) throw new Error("Model response had no assistant message");
    if (Array.isArray(message.tool_calls) && message.tool_calls.length) return { kind: "tool_calls", calls: message.tool_calls.map((call: any) => ({ id: call.id, name: call.function.name, input: JSON.parse(call.function.arguments || "{}") })) };
    return { kind: "text", text: message.content ?? "", usage: body.usage ? { inputTokens: body.usage.prompt_tokens ?? 0, outputTokens: body.usage.completion_tokens ?? 0 } : undefined };
  }
  async *stream(request: ModelRequest): AsyncIterable<ModelResponse> {
    const response = await fetch(`${this.options.baseUrl.replace(/\/$/, "")}/chat/completions`, { method: "POST", signal: request.signal, headers: { "content-type": "application/json", authorization: `Bearer ${this.options.apiKey}`, ...this.options.headers }, body: JSON.stringify({ model: this.options.model, messages: request.messages, stream: true, tools: request.tools?.map(tool => ({ type: "function", function: { name: tool.name, description: tool.description, parameters: tool.inputSchema } })) }) });
    if (!response.ok || !response.body) throw new Error(`Model stream failed (${response.status}): ${(await response.text()).slice(0, 500)}`);
    const decoder = new TextDecoder(); let pending = ""; let text = ""; const calls = new Map<number, { id: string; name: string; arguments: string }>();
    const consume = (chunk: string) => { for (const line of chunk.split("\n")) { if (!line.startsWith("data: ")) continue; const data = line.slice(6).trim(); if (!data || data === "[DONE]") continue; let payload: any; try { payload = JSON.parse(data); } catch { continue; } const delta = payload.choices?.[0]?.delta; if (!delta) continue; text += delta.content ?? ""; for (const call of delta.tool_calls ?? []) { const previous = calls.get(call.index) ?? { id: call.id ?? `call-${call.index}`, name: call.function?.name ?? "", arguments: "" }; previous.id = call.id ?? previous.id; previous.name = call.function?.name ?? previous.name; previous.arguments += call.function?.arguments ?? ""; calls.set(call.index, previous); } } };
    for await (const value of response.body as any as AsyncIterable<Uint8Array>) { pending += decoder.decode(value, { stream: true }); const lastBoundary = pending.lastIndexOf("\n\n"); if (lastBoundary >= 0) { consume(pending.slice(0, lastBoundary)); pending = pending.slice(lastBoundary + 2); } }
    consume(pending + decoder.decode()); const normalizedCalls = [...calls.values()].map(call => ({ id: call.id, name: call.name, input: JSON.parse(call.arguments || "{}") })); yield normalizedCalls.length ? { kind: "tool_calls", calls: normalizedCalls } : { kind: "text", text };
  }
}
export class AnthropicProvider implements ModelProvider {
  id = "anthropic"; capabilities = { toolCalling: true, structuredOutput: false, vision: true, reasoning: true, maxContextTokens: 200_000 };
  constructor(private readonly options: { apiKey: string; model: string; baseUrl?: string; maxTokens?: number }) {}
  async generate(request: ModelRequest): Promise<ModelResponse> { const system = request.messages.filter(message => message.role === "system").map(message => message.content).join("\n"); const messages = request.messages.filter(message => message.role !== "system").map(message => ({ role: message.role === "assistant" ? "assistant" : "user", content: message.content })); const response = await fetch(`${this.options.baseUrl ?? "https://api.anthropic.com/v1"}/messages`, { method: "POST", signal: request.signal, headers: { "content-type": "application/json", "x-api-key": this.options.apiKey, "anthropic-version": "2023-06-01" }, body: JSON.stringify({ model: this.options.model, max_tokens: this.options.maxTokens ?? 4096, system, messages, tools: request.tools?.map(tool => ({ name: tool.name, description: tool.description, input_schema: tool.inputSchema })) }) }); if (!response.ok) throw new Error(`Anthropic request failed (${response.status}): ${(await response.text()).slice(0, 500)}`); const body = await response.json() as any; const calls = (body.content ?? []).filter((block: any) => block.type === "tool_use").map((block: any) => ({ id: block.id, name: block.name, input: block.input })); if (calls.length) return { kind: "tool_calls", calls }; return { kind: "text", text: (body.content ?? []).filter((block: any) => block.type === "text").map((block: any) => block.text).join("\n"), usage: body.usage ? { inputTokens: body.usage.input_tokens ?? 0, outputTokens: body.usage.output_tokens ?? 0 } : undefined }; }
}
export class GeminiProvider implements ModelProvider {
  id = "gemini"; capabilities = { toolCalling: true, structuredOutput: true, vision: true, reasoning: true, maxContextTokens: 1_000_000 };
  constructor(private readonly options: { apiKey: string; model: string; baseUrl?: string }) {}
  async generate(request: ModelRequest): Promise<ModelResponse> { const endpoint = `${this.options.baseUrl ?? "https://generativelanguage.googleapis.com/v1beta"}/models/${this.options.model}:generateContent?key=${encodeURIComponent(this.options.apiKey)}`; const response = await fetch(endpoint, { method: "POST", signal: request.signal, headers: { "content-type": "application/json" }, body: JSON.stringify({ systemInstruction: { parts: request.messages.filter(message => message.role === "system").map(message => ({ text: message.content })) }, contents: request.messages.filter(message => message.role !== "system").map(message => ({ role: message.role === "assistant" ? "model" : "user", parts: [{ text: message.content }] })), tools: request.tools?.length ? [{ functionDeclarations: request.tools.map(tool => ({ name: tool.name, description: tool.description, parameters: tool.inputSchema })) }] : undefined }) }); if (!response.ok) throw new Error(`Gemini request failed (${response.status}): ${(await response.text()).slice(0, 500)}`); const body = await response.json() as any; const parts = body.candidates?.[0]?.content?.parts ?? []; const calls = parts.filter((part: any) => part.functionCall).map((part: any, index: number) => ({ id: `gemini-${index}`, name: part.functionCall.name, input: part.functionCall.args ?? {} })); if (calls.length) return { kind: "tool_calls", calls }; return { kind: "text", text: parts.map((part: any) => part.text ?? "").join("\n"), usage: body.usageMetadata ? { inputTokens: body.usageMetadata.promptTokenCount ?? 0, outputTokens: body.usageMetadata.candidatesTokenCount ?? 0 } : undefined }; }
}
/** OpenRouter and LM Studio expose the OpenAI Chat Completions contract. */
export class OpenRouterProvider extends OpenAICompatibleProvider { id = "openrouter"; constructor(options: Omit<OpenAICompatibleOptions, "baseUrl"> & { baseUrl?: string }) { super({ ...options, baseUrl: options.baseUrl ?? "https://openrouter.ai/api/v1" }); } }
/** DeepSeek exposes an OpenAI-compatible Chat Completions endpoint with tool calling. */
export class DeepSeekProvider extends OpenAICompatibleProvider {
  id = "deepseek";
  capabilities = { toolCalling: true, structuredOutput: true, vision: false, reasoning: true, maxContextTokens: 1_000_000 };
  constructor(options: Omit<OpenAICompatibleOptions, "baseUrl"> & { baseUrl?: string }) { super({ ...options, baseUrl: options.baseUrl ?? "https://api.deepseek.com" }); }
}
export class LmStudioProvider extends OpenAICompatibleProvider { id = "lm-studio"; constructor(options: Omit<OpenAICompatibleOptions, "baseUrl"> & { baseUrl?: string }) { super({ ...options, baseUrl: options.baseUrl ?? "http://127.0.0.1:1234/v1" }); } }
export class OllamaProvider implements ModelProvider {
  id = "ollama"; capabilities = { toolCalling: true, structuredOutput: true, vision: true, reasoning: false, maxContextTokens: 32_000 };
  constructor(private readonly options: { model: string; baseUrl?: string }) {}
  async generate(request: ModelRequest): Promise<ModelResponse> { const response = await fetch(`${this.options.baseUrl ?? "http://127.0.0.1:11434"}/api/chat`, { method: "POST", signal: request.signal, headers: { "content-type": "application/json" }, body: JSON.stringify({ model: this.options.model, stream: false, messages: request.messages, tools: request.tools?.map(tool => ({ type: "function", function: { name: tool.name, description: tool.description, parameters: tool.inputSchema } })) }) }); if (!response.ok) throw new Error(`Ollama request failed (${response.status}): ${(await response.text()).slice(0, 500)}`); const body = await response.json() as any; const calls = body.message?.tool_calls?.map((call: any, index: number) => ({ id: call.id ?? `ollama-${index}`, name: call.function?.name, input: call.function?.arguments ?? {} })) ?? []; return calls.length ? { kind: "tool_calls", calls } : { kind: "text", text: body.message?.content ?? "", usage: body.prompt_eval_count !== undefined ? { inputTokens: body.prompt_eval_count, outputTokens: body.eval_count ?? 0 } : undefined }; }
}
export class AzureOpenAIProvider implements ModelProvider {
  id = "azure-openai"; capabilities = { toolCalling: true, structuredOutput: true, vision: true, reasoning: true, maxContextTokens: 128_000 };
  constructor(private readonly options: { endpoint: string; apiKey: string; deployment: string; apiVersion?: string }) {}
  async generate(request: ModelRequest): Promise<ModelResponse> { const endpoint = `${this.options.endpoint.replace(/\/$/, "")}/openai/deployments/${encodeURIComponent(this.options.deployment)}/chat/completions?api-version=${encodeURIComponent(this.options.apiVersion ?? "2024-10-21")}`; const response = await fetch(endpoint, { method: "POST", signal: request.signal, headers: { "content-type": "application/json", "api-key": this.options.apiKey }, body: JSON.stringify({ messages: request.messages, tools: request.tools?.map(tool => ({ type: "function", function: { name: tool.name, description: tool.description, parameters: tool.inputSchema } })) }) }); if (!response.ok) throw new Error(`Azure OpenAI request failed (${response.status}): ${(await response.text()).slice(0, 500)}`); const body = await response.json() as any; const message = body.choices?.[0]?.message; if (!message) throw new Error("Azure OpenAI response had no assistant message"); const calls = message.tool_calls?.map((call: any) => ({ id: call.id, name: call.function.name, input: JSON.parse(call.function.arguments || "{}") })) ?? []; return calls.length ? { kind: "tool_calls", calls } : { kind: "text", text: message.content ?? "", usage: body.usage ? { inputTokens: body.usage.prompt_tokens ?? 0, outputTokens: body.usage.completion_tokens ?? 0 } : undefined }; }
}
export interface BedrockConverseClient { converse(request: { signal?: AbortSignal; modelId: string; system?: Array<{ text: string }>; messages: Array<{ role: "user" | "assistant"; content: Array<{ text?: string; toolResult?: unknown }> }>; toolConfig?: { tools: Array<{ toolSpec: { name: string; description: string; inputSchema: { json: Json } } }> } }): Promise<{ output?: { message?: { content?: Array<{ text?: string; toolUse?: { toolUseId: string; name: string; input: unknown } }> } }; usage?: { inputTokens?: number; outputTokens?: number } }> }
/** Native Bedrock Converse adapter; callers provide an authenticated AWS SDK client adapter. */
export class BedrockProvider implements ModelProvider {
  id = "bedrock"; capabilities = { toolCalling: true, structuredOutput: true, vision: true, reasoning: true, maxContextTokens: 200_000 };
  constructor(private readonly options: { model: string; client: BedrockConverseClient }) {}
  async generate(request: ModelRequest): Promise<ModelResponse> { const system = request.messages.filter(message => message.role === "system").map(message => ({ text: message.content })); const messages = request.messages.filter(message => message.role !== "system").map(message => ({ role: message.role === "assistant" ? "assistant" as const : "user" as const, content: [{ text: message.content }] })); const body = await this.options.client.converse({ signal: request.signal, modelId: this.options.model, system, messages, toolConfig: request.tools?.length ? { tools: request.tools.map(tool => ({ toolSpec: { name: tool.name, description: tool.description, inputSchema: { json: tool.inputSchema } } })) } : undefined }); const content = body.output?.message?.content ?? []; const calls = content.flatMap(item => item.toolUse ? [{ id: item.toolUse.toolUseId, name: item.toolUse.name, input: item.toolUse.input }] : []); return calls.length ? { kind: "tool_calls", calls } : { kind: "text", text: content.map(item => item.text ?? "").join("\n"), usage: body.usage ? { inputTokens: body.usage.inputTokens ?? 0, outputTokens: body.usage.outputTokens ?? 0 } : undefined }; }
}
