import { access, readdir, readFile, stat } from "node:fs/promises";
import { join, relative } from "node:path";
import { parser } from "@lezer/java";
import type { LanguagePlugin } from "../../../packages/language-services/src/index.js";
import type { Diagnostic, Repository, Symbol } from "../../../packages/shared/src/index.js";
const exists = (path: string) => access(path).then(() => true).catch(() => false);
function parseJava(source: string, file: string) { const symbols: Symbol[] = [], diagnostics: Diagnostic[] = [], references: Array<{ name: string; line: number }> = []; const starts = [0]; for (let index = 0; index < source.length; index++) if (source[index] === "\n") starts.push(index + 1); const lineAt = (offset: number) => { let low = 0, high = starts.length; while (low + 1 < high) { const middle = (low + high) >> 1; if (starts[middle]! <= offset) low = middle; else high = middle; } return low + 1; }; const kinds: Record<string, string> = { ClassDeclaration: "class", InterfaceDeclaration: "interface", EnumDeclaration: "enum", RecordDeclaration: "record", AnnotationTypeDeclaration: "annotation", MethodDeclaration: "method", ConstructorDeclaration: "constructor" }; const visit = (node: ReturnType<typeof parser.parse>["topNode"]) => { const kind = kinds[node.name]; if (kind) { const definition = node.getChild("Definition"); if (definition) symbols.push({ name: source.slice(definition.from, definition.to), kind, file, line: lineAt(definition.from), endLine: lineAt(node.to) }); } if (node.name === "TypeName") references.push({ name: source.slice(node.from, node.to), line: lineAt(node.from) }); if (node.type.isError) diagnostics.push({ file, line: lineAt(node.from), severity: "error", message: "Java syntax error" }); for (let child = node.firstChild; child; child = child.nextSibling) visit(child); }; visit(parser.parse(source).topNode); return { symbols, references, diagnostics: [...new Map(diagnostics.map(diagnostic => [`${diagnostic.file}:${diagnostic.line}:${diagnostic.message}`, diagnostic])).values()] }; }
async function javaFiles(root: string, at = root, output: string[] = []): Promise<string[]> { for (const entry of await readdir(at, { withFileTypes: true }).catch(() => [])) { if ([".git", ".agent", "target", "build"].includes(entry.name)) continue; const full = join(at, entry.name); if (entry.isDirectory()) await javaFiles(root, full, output); else if (entry.isFile() && entry.name.endsWith(".java")) output.push(relative(root, full)); } return output; }
export class JavaPlugin implements LanguagePlugin {
  id = "java"; private root?: string; private readonly cache = new Map<string, { fingerprint: string; result: ReturnType<typeof parseJava> }>();
  async detect(repository: Repository) { const maven = await exists(join(repository.root, "pom.xml")); const gradle = await exists(join(repository.root, "build.gradle")) || await exists(join(repository.root, "build.gradle.kts")); return { detected: maven || gradle, confidence: maven || gradle ? .95 : 0, evidence: [maven && "pom.xml", gradle && "build.gradle"].filter(Boolean) as string[] }; }
  async index(repository: Repository) { this.root = repository.root; this.cache.clear(); }
  private async parse(file: string) { if (!this.root) throw new Error("JavaPlugin.index(repository) must run first"); const path = join(this.root, file), metadata = await stat(path), fingerprint = `${metadata.mtimeMs}:${metadata.size}`, cached = this.cache.get(path); if (cached?.fingerprint === fingerprint) return cached.result; const result = parseJava(await readFile(path, "utf8"), file); this.cache.set(path, { fingerprint, result }); return result; }
  async getSymbols(file: string): Promise<Symbol[]> { return (await this.parse(file)).symbols; }
  async getReferences(symbol: string) { if (!this.root) return []; const references: Array<{ file: string; line: number; target: string }> = []; for (const file of await javaFiles(this.root)) for (const reference of (await this.parse(file)).references.filter(reference => reference.name === symbol)) references.push({ file, line: reference.line, target: symbol }); return references; }
  async getDiagnostics(files: string[]): Promise<Diagnostic[]> { if (!this.root) return []; return (await Promise.all(files.filter(file => file.endsWith(".java")).map(async file => (await this.parse(file)).diagnostics))).flat(); }
  async getBuildCommands(repository: Repository) { if (await exists(join(repository.root, "pom.xml"))) return [{ argv: ["mvn", "package", "-DskipTests"] }]; const gradle = await exists(join(repository.root, "gradlew")) ? "./gradlew" : "gradle"; return [{ argv: [gradle, "build", "-x", "test"] }]; }
  async getTestCommands(repository: Repository) { if (await exists(join(repository.root, "pom.xml"))) return [{ argv: ["mvn", "test"] }]; const gradle = await exists(join(repository.root, "gradlew")) ? "./gradlew" : "gradle"; return [{ argv: [gradle, "test"] }]; }
  async getFormatCommands() { return []; }
}
