import { describe, expect, it } from "vitest";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { RulePolicyEngine } from "../../packages/policy/src/index.js";
import { ToolRegistry, registerBuiltinTools } from "../../packages/tool-runtime/src/index.js";
import { LocalSandbox } from "../../packages/sandbox/src/index.js";
import { WorkspaceBoundary } from "../../packages/workspace/src/index.js";
describe("project command tools", () => it("discovers declared scripts and keeps formatting approval-gated", async () => { const root = await mkdtemp(join(tmpdir(), "harness-scripts-")); await writeFile(join(root, "package.json"), JSON.stringify({ packageManager: "pnpm@9", scripts: { test: "echo test", build: "echo build", lint: "echo lint", format: "echo format" } })); const registry = new ToolRegistry(); registerBuiltinTools(registry); const calls: string[][] = []; const sandbox = new LocalSandbox(); sandbox.execute = async command => { calls.push(command.argv); return { exitCode: 0, stdout: "ok", stderr: "", durationMs: 1 }; }; const context = { workspace: new WorkspaceBoundary(root), sandbox, approve: async (request: { tool: string }) => request.tool !== "run_format", policy: new RulePolicyEngine({ shell: "allow", edit: "allow" }) }; await registry.invoke("run_test", {}, context); await registry.invoke("run_build", {}, context); await registry.invoke("run_lint", {}, context); await expect(registry.invoke("run_format", {}, context)).rejects.toThrow("Policy ask"); expect(calls).toEqual([["pnpm", "test"], ["pnpm", "build"], ["pnpm", "lint"]]); }));

it("discovers Maven and Python tests without package scripts", async () => { const root = await mkdtemp(join(tmpdir(), "harness-polyglot-scripts-")); await writeFile(join(root, "pom.xml"), "<project />"); const registry = new ToolRegistry(); registerBuiltinTools(registry); const calls: string[][] = []; const sandbox = new LocalSandbox(); sandbox.execute = async command => { calls.push(command.argv); return { exitCode: 0, stdout: "ok", stderr: "", durationMs: 1 }; }; const context = { workspace: new WorkspaceBoundary(root), sandbox, approve: async (request: { tool: string }) => request.tool !== "run_format", policy: new RulePolicyEngine({ shell: "allow", edit: "allow" }) }; await registry.invoke("run_test", {}, context); await registry.invoke("run_build", {}, context); expect(calls).toEqual([["mvn", "test"], ["mvn", "package", "-DskipTests"]]); });

it("prefers the repository Maven Wrapper when it is available", async () => { const root = await mkdtemp(join(tmpdir(), "harness-maven-wrapper-")); await writeFile(join(root, "pom.xml"), "<project />"); await writeFile(join(root, "mvnw"), "#!/bin/sh"); const registry = new ToolRegistry(); registerBuiltinTools(registry); const calls: string[][] = []; const sandbox = new LocalSandbox(); sandbox.execute = async command => { calls.push(command.argv); return { exitCode: 0, stdout: "ok", stderr: "", durationMs: 1 }; }; const context = { workspace: new WorkspaceBoundary(root), sandbox, policy: new RulePolicyEngine({ shell: "allow" }), approve: async () => true }; await registry.invoke("run_test", {}, context); await registry.invoke("run_build", {}, context); expect(calls).toEqual([["./mvnw", "test"], ["./mvnw", "package", "-DskipTests"]]); });

it("prefers uv for Python tests and uses Python build isolation", async () => { const root = await mkdtemp(join(tmpdir(), "harness-python-scripts-")); await writeFile(join(root, "pyproject.toml"), "[project]\nname = 'example'\nversion = '0.1.0'\n"); await writeFile(join(root, "uv.lock"), "version = 1\n"); const registry = new ToolRegistry(); registerBuiltinTools(registry); const calls: string[][] = []; const sandbox = new LocalSandbox(); sandbox.execute = async command => { calls.push(command.argv); return { exitCode: 0, stdout: "ok", stderr: "", durationMs: 1 }; }; const context = { workspace: new WorkspaceBoundary(root), sandbox, approve: async (request: { tool: string }) => request.tool !== "run_format", policy: new RulePolicyEngine({ shell: "allow", edit: "allow" }) }; await registry.invoke("run_test", {}, context); await registry.invoke("run_build", {}, context); expect(calls).toEqual([["uv", "run", "pytest"], ["python", "-m", "build"]]); });
