import { describe, expect, it } from "vitest";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises"; import { tmpdir } from "node:os"; import { join } from "node:path";
import { AgentRuntime } from "../../packages/agent-core/src/index.js"; import { ProgressiveContextEngine } from "../../packages/context-engine/src/index.js"; import { ScriptedModelProvider } from "../../packages/model-gateway/src/index.js"; import { RulePolicyEngine } from "../../packages/policy/src/index.js"; import { InMemoryEventSink } from "../../packages/protocol/src/index.js"; import { LocalRepositoryKnowledgeProvider } from "../../packages/repository/src/index.js"; import { LocalSandbox } from "../../packages/sandbox/src/index.js"; import { ToolRegistry, registerBuiltinTools } from "../../packages/tool-runtime/src/index.js"; import { RepositoryVerificationPlanner, ToolVerificationRunner, type Verifier } from "../../packages/verification/src/index.js"; import { WorkspaceBoundary } from "../../packages/workspace/src/index.js";
describe("verification", () => it("discovers declared scripts and runs verification after an edit", async () => { const root = await mkdtemp(join(tmpdir(), "harness-verify-")); await writeFile(join(root, "package.json"), JSON.stringify({ scripts: { test: "vitest run", build: "tsc" } })); await writeFile(join(root, "note.txt"), "before"); expect((await new RepositoryVerificationPlanner(root).commands()).map(command => command.argv.join(" "))).toEqual(["npm test", "npm run build"]); const events = new InMemoryEventSink(); const tools = new ToolRegistry(); registerBuiltinTools(tools); const verifier: Verifier = { verify: async () => ({ passed: true, attempted: 1, skipped: 0, results: [] }) }; const runtime = new AgentRuntime(new ScriptedModelProvider([{ kind: "tool_calls", calls: [{ id: "1", name: "write_file", input: { path: "note.txt", content: "after" } }] }, { kind: "text", text: "finished" }]), tools, new ProgressiveContextEngine(new LocalRepositoryKnowledgeProvider({ root })), events, { workspace: new WorkspaceBoundary(root), sandbox: new LocalSandbox(), policy: new RulePolicyEngine({ write: "allow" }) }, verifier); const result = await runtime.run({ id: "1", prompt: "edit note", workspace: root }); expect(result.verification?.passed).toBe(true); expect(events.events.map(event => event.type)).toContain("verification.started"); }));

it("discovers verification commands in nested projects", async () => { const root = await mkdtemp(join(tmpdir(), "harness-verify-nested-")); const frontend = join(root, "frontend"); const backend = join(root, "backend"); await mkdir(frontend); await mkdir(backend); await writeFile(join(frontend, "package.json"), JSON.stringify({ scripts: { build: "vite build" } })); await writeFile(join(backend, "pom.xml"), "<project />"); const commands = await new RepositoryVerificationPlanner(root).commands(); expect(commands.map(command => ({ argv: command.argv, cwd: command.cwd }))).toEqual([{ argv: ["mvn", "test"], cwd: "backend" }, { argv: ["npm", "run", "build"], cwd: "frontend" }]); });

it("uses a Maven Wrapper for Maven verification when the repository provides one", async () => { const root = await mkdtemp(join(tmpdir(), "harness-verify-maven-wrapper-")); await writeFile(join(root, "pom.xml"), "<project />"); await writeFile(join(root, "mvnw"), "#!/bin/sh"); const commands = await new RepositoryVerificationPlanner(root).commands(); expect(commands.map(command => command.argv)).toEqual([["./mvnw", "test"]]); });

it("replans verification after an agent creates a project manifest", async () => { const root = await mkdtemp(join(tmpdir(), "harness-verify-replan-")); const frontend = join(root, "frontend"); await mkdir(frontend); await writeFile(join(frontend, "package.json"), JSON.stringify({ scripts: { build: "vite build" } })); const tools = new ToolRegistry(); registerBuiltinTools(tools); const sandbox = new LocalSandbox(); const calls: Array<{ argv: string[]; cwd?: string }> = []; sandbox.execute = async command => { calls.push({ argv: command.argv, cwd: command.cwd }); return { exitCode: 0, stdout: "ok", stderr: "", durationMs: 1 }; }; const context = { workspace: new WorkspaceBoundary(root), sandbox, policy: new RulePolicyEngine({ shell: "allow" }), approve: async () => true }; const result = await new ToolVerificationRunner(() => new RepositoryVerificationPlanner(root).commands(), tools, context).verify(); expect(result).toMatchObject({ passed: true, attempted: 1 }); expect(calls).toEqual([{ argv: ["npm", "run", "build"], cwd: frontend }]); });

it("reports policy-blocked verification as incomplete rather than passed", async () => { const root = await mkdtemp(join(tmpdir(), "harness-verify-policy-")); const tools = new ToolRegistry(); registerBuiltinTools(tools); const context = { workspace: new WorkspaceBoundary(root), sandbox: new LocalSandbox(), policy: new RulePolicyEngine({ shell: "ask" }) }; const result = await new ToolVerificationRunner([{ argv: ["npm", "test"], risk: "safe" }], tools, context).verify(); expect(result).toMatchObject({ passed: false, attempted: 0, skipped: 1 }); });
