import type { Task } from "../../shared/src/index.js";
import type { RepositoryKnowledgeProvider, RepositoryContext } from "../../repository/src/index.js";
export interface ContextItem { source: "filesystem" | "tree-sitter" | "lsp" | "git" | "graphify" | "search" | "framework"; relevance: number; tokenCost: number; content: string }
export interface ContextPackage { items: ContextItem[]; repository: RepositoryContext; estimatedTokens: number }
export interface ContextEngine { buildContext(task: Task): Promise<ContextPackage>; expandContext(reason: string): Promise<ContextPackage>; compactContext(): Promise<void> }
export class ProgressiveContextEngine implements ContextEngine {
  private last?: ContextPackage; constructor(private readonly provider: RepositoryKnowledgeProvider, private readonly tokenBudget = 8_000) {}
  async buildContext(task: Task): Promise<ContextPackage> { const repository = await this.provider.getRelevantContext(task); const items: ContextItem[] = [{ source: "filesystem", relevance: .7, tokenCost: Math.ceil(JSON.stringify(repository.map).length / 4), content: JSON.stringify(repository.map) }, { source: "search", relevance: .95, tokenCost: Math.ceil(JSON.stringify(repository.symbols).length / 4), content: `Relevant symbols: ${JSON.stringify(repository.symbols)}` }, { source: "search", relevance: .95, tokenCost: Math.ceil(JSON.stringify(repository.snippets).length / 4), content: `Relevant source excerpts: ${JSON.stringify(repository.snippets)}` }, { source: "framework", relevance: .95, tokenCost: Math.ceil(JSON.stringify(repository.framework ?? []).length / 4), content: `Framework topology: ${JSON.stringify(repository.framework ?? [])}` }, { source: "filesystem", relevance: .8, tokenCost: Math.ceil(JSON.stringify(repository.tests).length / 4), content: `Related tests: ${JSON.stringify(repository.tests)}` }]; const ranked = items.sort((a, b) => b.relevance / Math.max(b.tokenCost, 1) - a.relevance / Math.max(a.tokenCost, 1)); const selected: ContextItem[] = []; let used = 0; for (const item of ranked) { if (used + item.tokenCost <= this.tokenBudget || !selected.length) { selected.push(item); used += item.tokenCost; } } return this.last = { items: selected, repository, estimatedTokens: used }; }
  async expandContext(reason: string) { return this.buildContext({ id: "expansion", prompt: reason, workspace: "" }); }
  async compactContext() { if (this.last) this.last.items = this.last.items.slice(0, 1); }
}
